model_params:
  max_item_num: 10
  item_num: [1,2,3,4,5,6,7,8,9,10]
  num_neurons: 512
  tau: 50
  dt: 10
  ILC_noise: 0.01
  process_noise: 0.5
  decode_noise: 0.0
  positive_input: false
  T_init: 20
  T_stimi: 400
  T_delay: 500
  T_decode: 300

training_params:
  train_rnn: true
  from_scratch: true
  num_epochs: 500000
  eta: 0.0001
  lambda_reg: 0.0005
  lambda_err: 1.0
  num_trials: 512
  logging_period: 100
  early_stop_patience: 600
  adaptive_lr_patience: 250

model_and_logging_params:
  rnn_name: ""
  cuda_device: 1
  error_dist_bool: false

fpf_params:
  fpf_bool: false
  fpf_pca_bool: true
  fpf_names: ["stimuli", "decode"]
  fpf_trials: 64
  fpf_N_init: 256
  fpf_noise_scale: 0.0
  fpf_hps:
    max_iters: 500
    lr_init: 1.0
    outlier_distance_scale: 10.0
    verbose: false
    super_verbose: false