model_params:
  max_item_num: 1
  item_num: [1]
  num_neurons: 256
  tau: 50
  dt: 10
  ILC_noise: 0.01
  process_noise: 0.5
  decode_noise: 0.0
  positive_input: true
  T_init: 20
  T_stimi: 400
  T_delay: 0
  T_decode: 800

training_params:
  train_rnn: true
  from_scratch: false
  num_epochs: 500000
  eta: 0.0001
  lambda_reg: 0.0005
  lambda_err: 1.0
  num_trials: 512
  logging_period: 10
  early_stop_patience: 100
  adaptive_lr_patience: 60

model_and_logging_params:
  rnn_name: "TMR-ilc-2"
  cuda_device: 1
  error_dist_bool: false

fpf_params:
  fpf_bool: true
  fpf_pca_bool: true
  fpf_names: ["stimuli", "decode"]
  fpf_trials: 64
  fpf_N_init: 512
  fpf_noise_scale: 0.0
  fpf_hps:
    max_iters: 500
    lr_init: 1.0
    outlier_distance_scale: 10.0
    verbose: false
    super_verbose: false